name: Playwright Tests on Custom Runner Extended

on:
  push:
    branches: [main]
  workflow_dispatch:

env:
  URL: ${{ secrets.URL }}
  API_URL: ${{ secrets.API_URL }}
  USER_NAME: ${{ secrets.USER_NAME }}
  EMAIL: ${{ secrets.EMAIL }}
  PASSWORD: ${{ secrets.PASSWORD }}

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  setup-and-smoke-test:
    name: Setup and Smoke Test
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Playwright Setup on runner
        uses: ./.github/actions/playwright-setup

      - name: Run Smoke Test
        id: smoke
        run: npm run smoke

      - name: Upload Smoke Blob Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: blob-report-smoke
          path: smoke-blob-report

  api-test:
    name: API test
    needs: setup-and-smoke-test
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Playwright Setup on Runner
        uses: ./.github/actions/playwright-setup

      - name: Run API tests
        id: api
        run: npm run api

      - name: Upload API blob Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: blob-report-api
          path: api-blob-report

  merge-report:
    name: Merge Report
    if: always()
    needs: [setup-and-smoke-test, api-test]
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Install Dependencies
        run: npm ci

      - name: Download blob reports
        uses: actions/download-artifact@v4
        with:
          path: all-blob-reports
          pattern: blob-report-*
          merge-multiple: true

      - name: Merge into HTML Report
        run: npx playwright merge-reports --reporter html ./all-blob-reports

      - name: Upload HTML report
        uses: actions/upload-artifact@v4
        with:
          name: Merged HTML Reports
          path: playwright-report
          retention-days: 3

  build-report:
    name: Build Report
    if: always()
    needs: merge-report
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download Merged HTML Reports
        uses: actions/download-artifact@v4
        with:
          name: Merged HTML Reports
          path: ./_site

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./_site

  depoloy-report:
    name: Deploy Report
    if: always()
    needs: build-report
    environment:
      name: github-pages
      url: "https://YordanPopov.github.io/idea-center-PW-Framework/"
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
